### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by asodhani21**

### CODE REVIEW

**Comment by grace4ch** [comment]
nice.

**Comment by hanchoe13** [comment]
Looking good

**Review by ReginaeE — APPROVED** [review]

**Review by hanchoe13 — APPROVED** [review]

**Review by grace4ch — APPROVED** [review]
readme approved

**Review by ReginaeE — APPROVED** [review]

**Review by asodhani21 — COMMENTED** [review]
w

**Review by funkyvoong — APPROVED** [review]

**Pull request merged**
