### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by asodhani21**
This is the database of all the racist deeds in our focal point in Longmeadow, MA in the early 1900s, and a file of deed images (TIFF) that accompanies this database.

### CODE REVIEW

**Comment by hanchoe13** [comment]
Looks good

**Comment by grace4ch** [comment]
looks good :)

**Review by ReginaeE — APPROVED** [review]

**Review by hanchoe13 — APPROVED** [review]

**Review by grace4ch — APPROVED** [review]
file uploaded approved

**Review by ReginaeE — APPROVED** [review]

**Review by ReginaeE — APPROVED** [review]
Great work here team

**Review by funkyvoong — APPROVED** [review]

**Pull request merged**
